<?php

use Illuminate\Database\Seeder;

class BlocksTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('blocks')->delete();
        
        \DB::table('blocks')->insert(array (
            0 => 
            array (
                'id' => 39,
                'uuid' => 'f62db5d2-218c-11ea-b13f-000c29f165c4',
                'type' => 1,
                'sub_type' => 6,
                'title' => 'Top Schools We Cover',
                'slug' => 'school-section',
                'sub_title' => '',
                'content' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat',
                'note' => '',
                'subject_title_1' => NULL,
                'subject_title_1_content' => NULL,
                'subject_title_2' => NULL,
                'subject_title_2_content' => NULL,
                'subject_title_3' => NULL,
                'subject_title_3_content' => NULL,
                'subject_title_4' => NULL,
                'subject_title_4_content' => NULL,
                'exam_format_title_1' => NULL,
                'exam_format_title_1_content' => NULL,
                'exam_format_title_2' => NULL,
                'exam_format_title_2_content' => NULL,
                'project_type' => 3,
                'created_at' => '2020-09-30 13:24:41',
                'updated_at' => '2020-09-30 12:51:47',
                'deleted_at' => NULL,
                'slider_1_title' => NULL,
                'slider_1_sub_title' => NULL,
                'slider_1_description' => NULL,
                'slider_2_title' => NULL,
                'slider_2_sub_title' => NULL,
                'slider_2_description' => NULL,
                'slider_3_title' => NULL,
                'slider_3_sub_title' => NULL,
                'slider_3_description' => NULL,
                'title_1' => NULL,
                'content_1' => NULL,
                'title_2' => NULL,
                'content_2' => NULL,
                'title_3' => NULL,
                'content_3' => NULL,
                'title_4' => NULL,
                'content_4' => NULL,
                'title_5' => NULL,
                'content_5' => NULL,
                'title_6' => NULL,
                'content_6' => NULL,
                'image_1' => NULL,
                'image_2' => NULL,
                'image_3' => NULL,
                'image_4' => NULL,
                'image_5' => NULL,
                'image_6' => NULL,
                'video_url' => NULL,
            ),
            1 => 
            array (
                'id' => 38,
                'uuid' => 'f62db5d2-218c-11ea-b13f-000c29f165c3',
                'type' => 1,
                'sub_type' => 5,
                'title' => 'Thousands of children have benefited from our mock tests and we are delighted to have many returning parents.',
                'slug' => 'video-section',
                'sub_title' => '',
                'content' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat',
                'note' => '',
                'subject_title_1' => '',
                'subject_title_1_content' => '',
                'subject_title_2' => '',
                'subject_title_2_content' => '',
                'subject_title_3' => '',
                'subject_title_3_content' => '',
                'subject_title_4' => '',
                'subject_title_4_content' => '',
                'exam_format_title_1' => '',
                'exam_format_title_1_content' => '',
                'exam_format_title_2' => '',
                'exam_format_title_2_content' => '',
                'project_type' => 3,
                'created_at' => '2020-09-30 13:24:41',
                'updated_at' => '2021-03-23 07:34:16',
                'deleted_at' => NULL,
                'slider_1_title' => '',
                'slider_1_sub_title' => '',
                'slider_1_description' => '',
                'slider_2_title' => '',
                'slider_2_sub_title' => '',
                'slider_2_description' => '',
                'slider_3_title' => '',
                'slider_3_sub_title' => '',
                'slider_3_description' => '',
                'title_1' => '',
                'content_1' => '',
                'title_2' => '',
                'content_2' => '',
                'title_3' => '',
                'content_3' => '',
                'title_4' => '',
                'content_4' => '',
                'title_5' => '',
                'content_5' => '',
                'title_6' => '',
                'content_6' => '',
                'image_1' => NULL,
                'image_2' => NULL,
                'image_3' => NULL,
                'image_4' => NULL,
                'image_5' => NULL,
                'image_6' => NULL,
                'video_url' => 'yAoLSRbwxL8',
            ),
            2 => 
            array (
                'id' => 41,
                'uuid' => 'f62db5d2-218c-11ea-b13f-000c29f165c6',
                'type' => 1,
                'sub_type' => 7,
                'title' => 'We Help Kids Grow Their Potential',
                'slug' => 'help-section',
                'sub_title' => '',
                'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequa',
                'note' => '',
                'subject_title_1' => '',
                'subject_title_1_content' => '',
                'subject_title_2' => '',
                'subject_title_2_content' => '',
                'subject_title_3' => '',
                'subject_title_3_content' => '',
                'subject_title_4' => '',
                'subject_title_4_content' => '',
                'exam_format_title_1' => '',
                'exam_format_title_1_content' => '',
                'exam_format_title_2' => '',
                'exam_format_title_2_content' => '',
                'project_type' => 3,
                'created_at' => '2020-09-30 13:24:41',
                'updated_at' => '2021-03-23 07:37:47',
                'deleted_at' => NULL,
                'slider_1_title' => '',
                'slider_1_sub_title' => '',
                'slider_1_description' => '',
                'slider_2_title' => '',
                'slider_2_sub_title' => '',
                'slider_2_description' => '',
                'slider_3_title' => '',
                'slider_3_sub_title' => '',
                'slider_3_description' => '',
                'title_1' => 'Loreum Ipsum',
                'content_1' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diamLorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diamLorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam',
                'title_2' => 'Loreum Ipsum',
                'content_2' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diamLorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diamLorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam',
                'title_3' => 'Loreum Ipsum',
                'content_3' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diamLorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diamLorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam',
                'title_4' => 'Loreum Ipsum',
                'content_4' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diamLorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diamLorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam',
                'title_5' => '',
                'content_5' => '',
                'title_6' => '',
                'content_6' => '',
                'image_1' => 'C:\\xampp\\tmp\\phpEBC.tmp',
                'image_2' => 'C:\\xampp\\tmp\\phpEBD.tmp',
                'image_3' => 'C:\\xampp\\tmp\\phpEBE.tmp',
                'image_4' => 'C:\\xampp\\tmp\\phpEBF.tmp',
                'image_5' => NULL,
                'image_6' => NULL,
                'video_url' => NULL,
            ),
            3 => 
            array (
                'id' => 34,
                'uuid' => 'f62db5d2-218c-11ea-b13f-000c29f164c9',
                'type' => 1,
                'sub_type' => 2,
                'title' => 'Our Modules',
                'slug' => 'our-module-section',
                'sub_title' => '',
                'content' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat',
                'note' => '',
                'subject_title_1' => NULL,
                'subject_title_1_content' => NULL,
                'subject_title_2' => NULL,
                'subject_title_2_content' => NULL,
                'subject_title_3' => NULL,
                'subject_title_3_content' => NULL,
                'subject_title_4' => NULL,
                'subject_title_4_content' => NULL,
                'exam_format_title_1' => NULL,
                'exam_format_title_1_content' => NULL,
                'exam_format_title_2' => NULL,
                'exam_format_title_2_content' => NULL,
                'project_type' => 3,
                'created_at' => '2020-09-30 13:24:41',
                'updated_at' => '2020-10-01 13:07:05',
                'deleted_at' => NULL,
                'slider_1_title' => NULL,
                'slider_1_sub_title' => NULL,
                'slider_1_description' => NULL,
                'slider_2_title' => NULL,
                'slider_2_sub_title' => NULL,
                'slider_2_description' => NULL,
                'slider_3_title' => NULL,
                'slider_3_sub_title' => NULL,
                'slider_3_description' => NULL,
                'title_1' => 'AshACE Papers',
                'content_1' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis',
                'title_2' => 'AshACE Mock Exams',
                'content_2' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis',
                'title_3' => 'AshACE Practice',
                'content_3' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis',
                'title_4' => NULL,
                'content_4' => NULL,
                'title_5' => NULL,
                'content_5' => NULL,
                'title_6' => NULL,
                'content_6' => NULL,
                'image_1' => NULL,
                'image_2' => NULL,
                'image_3' => NULL,
                'image_4' => NULL,
                'image_5' => NULL,
                'image_6' => NULL,
                'video_url' => NULL,
            ),
            4 => 
            array (
                'id' => 4,
                'uuid' => '429841c2-2199-11ea-b13f-000c29f164c3',
                'type' => 1,
                'sub_type' => 4,
                'title' => 'Covers All Exam Formats',
                'slug' => 'home-exam-formats',
                'sub_title' => NULL,
                'content' => NULL,
                'note' => NULL,
                'subject_title_1' => NULL,
                'subject_title_1_content' => NULL,
                'subject_title_2' => NULL,
                'subject_title_2_content' => NULL,
                'subject_title_3' => NULL,
                'subject_title_3_content' => NULL,
                'subject_title_4' => NULL,
                'subject_title_4_content' => NULL,
                'exam_format_title_1' => 'Standard Format_01',
            'exam_format_title_1_content' => 'means you write long answers (English), show workings (Maths). This format is usually applicable to most independent schools',
                'exam_format_title_2' => 'Standard Format_02',
                'exam_format_title_2_content' => 'multiple-choice questions format means you are given 4 or 5 options to choose from. Mark your answers on an answer sheet. This format is usually applicable to most grammar schools',
                'project_type' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-10-02 11:49:03',
                'deleted_at' => NULL,
                'slider_1_title' => NULL,
                'slider_1_sub_title' => NULL,
                'slider_1_description' => NULL,
                'slider_2_title' => NULL,
                'slider_2_sub_title' => NULL,
                'slider_2_description' => NULL,
                'slider_3_title' => NULL,
                'slider_3_sub_title' => NULL,
                'slider_3_description' => NULL,
                'title_1' => NULL,
                'content_1' => NULL,
                'title_2' => NULL,
                'content_2' => NULL,
                'title_3' => NULL,
                'content_3' => NULL,
                'title_4' => NULL,
                'content_4' => NULL,
                'title_5' => NULL,
                'content_5' => NULL,
                'title_6' => NULL,
                'content_6' => NULL,
                'image_1' => NULL,
                'image_2' => NULL,
                'image_3' => NULL,
                'image_4' => NULL,
                'image_5' => NULL,
                'image_6' => NULL,
                'video_url' => NULL,
            ),
            5 => 
            array (
                'id' => 9,
                'uuid' => '6b717ed5-219b-11ea-b13f-000c29f164c3',
                'type' => 2,
                'sub_type' => 9,
                'title' => 'Minds Behind The Scene',
                'slug' => 'aboutus-mind-behind-the-scene',
                'sub_title' => 'Lorem Ipsum 1',
                'content' => 'motivational leadership and cooperative team pave our way to success in achieving our mutual Gemoo vision 1.',
                'note' => 'Director 1',
                'subject_title_1' => 'Lorem Ipsum 2',
                'subject_title_1_content' => 'motivational leadership and cooperative team pave our way to success in achieving our mutual Gemoo vision 2.',
                'subject_title_2' => 'Lorem Ipsum 3',
                'subject_title_2_content' => 'motivational leadership and cooperative team pave our way to success in achieving our mutual Gemoo vision 3.',
                'subject_title_3' => 'Lorem Ipsum 4',
                'subject_title_3_content' => 'motivational leadership and cooperative team pave our way to success in achieving our mutual Gemoo vision 4.',
                'subject_title_4' => 'Director 2',
                'subject_title_4_content' => '',
                'exam_format_title_1' => 'Director 3',
                'exam_format_title_1_content' => '',
                'exam_format_title_2' => 'Director 4',
                'exam_format_title_2_content' => NULL,
                'project_type' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-10-05 08:14:42',
                'deleted_at' => NULL,
                'slider_1_title' => NULL,
                'slider_1_sub_title' => NULL,
                'slider_1_description' => NULL,
                'slider_2_title' => NULL,
                'slider_2_sub_title' => NULL,
                'slider_2_description' => NULL,
                'slider_3_title' => NULL,
                'slider_3_sub_title' => NULL,
                'slider_3_description' => NULL,
                'title_1' => NULL,
                'content_1' => NULL,
                'title_2' => NULL,
                'content_2' => NULL,
                'title_3' => NULL,
                'content_3' => NULL,
                'title_4' => NULL,
                'content_4' => NULL,
                'title_5' => NULL,
                'content_5' => NULL,
                'title_6' => NULL,
                'content_6' => NULL,
                'image_1' => NULL,
                'image_2' => NULL,
                'image_3' => NULL,
                'image_4' => NULL,
                'image_5' => NULL,
                'image_6' => NULL,
                'video_url' => NULL,
            ),
            6 => 
            array (
                'id' => 2,
                'uuid' => '2e6feacf-218e-11ea-b13f-000c29f164c3',
                'type' => 1,
                'sub_type' => 2,
                'title' => 'Designed By Experts',
                'slug' => 'home-designed-by-experts',
                'sub_title' => 'And Classroom Tested',
                'content' => 'All papers are designed by experts have also helped large number of students to pass grammar and independent school exams. Our students are generally high-achievers and have attained high scores in the recent exams such as 280/280 in QE Boys, 423/423 in Kent, Top 180 in Bexley and over 250 in Newstead Wood.

The papers are meticulously designed and classroom tested. Students have given feedback on appropriateness of content, quality of questions and ironed out human errors. Our papers are and are ‘ﬁt for purpose’.
Test',
                'note' => NULL,
                'subject_title_1' => NULL,
                'subject_title_1_content' => NULL,
                'subject_title_2' => NULL,
                'subject_title_2_content' => NULL,
                'subject_title_3' => NULL,
                'subject_title_3_content' => NULL,
                'subject_title_4' => NULL,
                'subject_title_4_content' => NULL,
                'exam_format_title_1' => NULL,
                'exam_format_title_1_content' => NULL,
                'exam_format_title_2' => NULL,
                'exam_format_title_2_content' => NULL,
                'project_type' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-10-05 08:26:59',
                'deleted_at' => NULL,
                'slider_1_title' => NULL,
                'slider_1_sub_title' => NULL,
                'slider_1_description' => NULL,
                'slider_2_title' => NULL,
                'slider_2_sub_title' => NULL,
                'slider_2_description' => NULL,
                'slider_3_title' => NULL,
                'slider_3_sub_title' => NULL,
                'slider_3_description' => NULL,
                'title_1' => NULL,
                'content_1' => NULL,
                'title_2' => NULL,
                'content_2' => NULL,
                'title_3' => NULL,
                'content_3' => NULL,
                'title_4' => NULL,
                'content_4' => NULL,
                'title_5' => NULL,
                'content_5' => NULL,
                'title_6' => NULL,
                'content_6' => NULL,
                'image_1' => NULL,
                'image_2' => NULL,
                'image_3' => NULL,
                'image_4' => NULL,
                'image_5' => NULL,
                'image_6' => NULL,
                'video_url' => NULL,
            ),
            7 => 
            array (
                'id' => 7,
                'uuid' => '8cf364dd-219b-11ea-b13f-000c29f164c3',
                'type' => 2,
                'sub_type' => 7,
                'title' => 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',
                'slug' => 'aboutus-main-section',
                'sub_title' => NULL,
                'content' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'note' => NULL,
                'subject_title_1' => NULL,
                'subject_title_1_content' => NULL,
                'subject_title_2' => NULL,
                'subject_title_2_content' => NULL,
                'subject_title_3' => NULL,
                'subject_title_3_content' => NULL,
                'subject_title_4' => NULL,
                'subject_title_4_content' => NULL,
                'exam_format_title_1' => NULL,
                'exam_format_title_1_content' => NULL,
                'exam_format_title_2' => NULL,
                'exam_format_title_2_content' => NULL,
                'project_type' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-10-05 08:15:51',
                'deleted_at' => NULL,
                'slider_1_title' => NULL,
                'slider_1_sub_title' => NULL,
                'slider_1_description' => NULL,
                'slider_2_title' => NULL,
                'slider_2_sub_title' => NULL,
                'slider_2_description' => NULL,
                'slider_3_title' => NULL,
                'slider_3_sub_title' => NULL,
                'slider_3_description' => NULL,
                'title_1' => NULL,
                'content_1' => NULL,
                'title_2' => NULL,
                'content_2' => NULL,
                'title_3' => NULL,
                'content_3' => NULL,
                'title_4' => NULL,
                'content_4' => NULL,
                'title_5' => NULL,
                'content_5' => NULL,
                'title_6' => NULL,
                'content_6' => NULL,
                'image_1' => NULL,
                'image_2' => NULL,
                'image_3' => NULL,
                'image_4' => NULL,
                'image_5' => NULL,
                'image_6' => NULL,
                'video_url' => NULL,
            ),
            8 => 
            array (
                'id' => 5,
                'uuid' => '913fbcee-219a-11ea-b13f-000c29f164c3',
                'type' => 1,
                'sub_type' => 5,
                'title' => 'Covers All Exam Styles',
                'slug' => 'home-exam-styles',
                'sub_title' => NULL,
            'content' => 'The school may choose to take the exam in GL style or CEM style. The formats vary a lot in terms of content, difﬁculty and sp We also cover the formats of some super-selective schools (QE, Wilson, St. Olave’s etc.) design their own exam papers.aa',
                'note' => NULL,
                'subject_title_1' => NULL,
                'subject_title_1_content' => NULL,
                'subject_title_2' => NULL,
                'subject_title_2_content' => NULL,
                'subject_title_3' => NULL,
                'subject_title_3_content' => NULL,
                'subject_title_4' => NULL,
                'subject_title_4_content' => NULL,
                'exam_format_title_1' => NULL,
                'exam_format_title_1_content' => NULL,
                'exam_format_title_2' => NULL,
                'exam_format_title_2_content' => NULL,
                'project_type' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-10-05 08:28:12',
                'deleted_at' => NULL,
                'slider_1_title' => NULL,
                'slider_1_sub_title' => NULL,
                'slider_1_description' => NULL,
                'slider_2_title' => NULL,
                'slider_2_sub_title' => NULL,
                'slider_2_description' => NULL,
                'slider_3_title' => NULL,
                'slider_3_sub_title' => NULL,
                'slider_3_description' => NULL,
                'title_1' => NULL,
                'content_1' => NULL,
                'title_2' => NULL,
                'content_2' => NULL,
                'title_3' => NULL,
                'content_3' => NULL,
                'title_4' => NULL,
                'content_4' => NULL,
                'title_5' => NULL,
                'content_5' => NULL,
                'title_6' => NULL,
                'content_6' => NULL,
                'image_1' => NULL,
                'image_2' => NULL,
                'image_3' => NULL,
                'image_4' => NULL,
                'image_5' => NULL,
                'image_6' => NULL,
                'video_url' => NULL,
            ),
            9 => 
            array (
                'id' => 3,
                'uuid' => 'f82230b3-218f-11ea-b13f-000c29f164c3',
                'type' => 1,
                'sub_type' => 3,
                'title' => 'Covers All Subjects',
                'slug' => 'home-all-subjects',
                'sub_title' => NULL,
                'content' => NULL,
                'note' => NULL,
                'subject_title_1' => 'English',
                'subject_title_1_content' => 'Comprehension, SPaG

(Spelling, Punctuation and Grammar),
Cloze, Creative Writing',
                'subject_title_2' => 'Verbal Reasoning',
                'subject_title_2_content' => 'All 21 Types',
                'subject_title_3' => 'Maths',
                'subject_title_3_content' => 'Over 35 Topics',
                'subject_title_4' => 'Non-Verbal Reasoning',
                'subject_title_4_content' => 'All Types',
                'exam_format_title_1' => NULL,
                'exam_format_title_1_content' => NULL,
                'exam_format_title_2' => NULL,
                'exam_format_title_2_content' => NULL,
                'project_type' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-08-13 11:54:21',
                'deleted_at' => NULL,
                'slider_1_title' => NULL,
                'slider_1_sub_title' => NULL,
                'slider_1_description' => NULL,
                'slider_2_title' => NULL,
                'slider_2_sub_title' => NULL,
                'slider_2_description' => NULL,
                'slider_3_title' => NULL,
                'slider_3_sub_title' => NULL,
                'slider_3_description' => NULL,
                'title_1' => NULL,
                'content_1' => NULL,
                'title_2' => NULL,
                'content_2' => NULL,
                'title_3' => NULL,
                'content_3' => NULL,
                'title_4' => NULL,
                'content_4' => NULL,
                'title_5' => NULL,
                'content_5' => NULL,
                'title_6' => NULL,
                'content_6' => NULL,
                'image_1' => NULL,
                'image_2' => NULL,
                'image_3' => NULL,
                'image_4' => NULL,
                'image_5' => NULL,
                'image_6' => NULL,
                'video_url' => NULL,
            ),
            10 => 
            array (
                'id' => 6,
                'uuid' => '30b97008-219b-11ea-b13f-000c29f164c3',
                'type' => 2,
                'sub_type' => 6,
                'title' => 'Lorem ipsum dolor sit amet dd',
                'slug' => 'aboutus-banner-section',
                'sub_title' => 'Consectetur adipiscing elit a',
                'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum rhoncus accumsan nisi suscipit tincidunt. Etiam vestibulum sem felis, in interdum sapien mollis sit amet.

Vestibulum rhoncus accumsan nisi suscipit tincidunt. Etiam vestibulum sem felis, in interdum sapien mollis sit amet. test.',
                'note' => NULL,
                'subject_title_1' => NULL,
                'subject_title_1_content' => NULL,
                'subject_title_2' => NULL,
                'subject_title_2_content' => NULL,
                'subject_title_3' => NULL,
                'subject_title_3_content' => NULL,
                'subject_title_4' => NULL,
                'subject_title_4_content' => NULL,
                'exam_format_title_1' => NULL,
                'exam_format_title_1_content' => NULL,
                'exam_format_title_2' => NULL,
                'exam_format_title_2_content' => NULL,
                'project_type' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-10-05 08:17:02',
                'deleted_at' => NULL,
                'slider_1_title' => NULL,
                'slider_1_sub_title' => NULL,
                'slider_1_description' => NULL,
                'slider_2_title' => NULL,
                'slider_2_sub_title' => NULL,
                'slider_2_description' => NULL,
                'slider_3_title' => NULL,
                'slider_3_sub_title' => NULL,
                'slider_3_description' => NULL,
                'title_1' => NULL,
                'content_1' => NULL,
                'title_2' => NULL,
                'content_2' => NULL,
                'title_3' => NULL,
                'content_3' => NULL,
                'title_4' => NULL,
                'content_4' => NULL,
                'title_5' => NULL,
                'content_5' => NULL,
                'title_6' => NULL,
                'content_6' => NULL,
                'image_1' => NULL,
                'image_2' => NULL,
                'image_3' => NULL,
                'image_4' => NULL,
                'image_5' => NULL,
                'image_6' => NULL,
                'video_url' => NULL,
            ),
            11 => 
            array (
                'id' => 10,
                'uuid' => '9010944f-219b-11ea-b13f-000c29f164c3',
                'type' => 2,
                'sub_type' => 10,
                'title' => 'sub section',
                'slug' => 'aboutus-sub-section',
                'sub_title' => NULL,
                'content' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>',
                'note' => NULL,
                'subject_title_1' => NULL,
                'subject_title_1_content' => NULL,
                'subject_title_2' => NULL,
                'subject_title_2_content' => NULL,
                'subject_title_3' => NULL,
                'subject_title_3_content' => NULL,
                'subject_title_4' => NULL,
                'subject_title_4_content' => NULL,
                'exam_format_title_1' => NULL,
                'exam_format_title_1_content' => NULL,
                'exam_format_title_2' => NULL,
                'exam_format_title_2_content' => NULL,
                'project_type' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-01-01 10:19:59',
                'deleted_at' => NULL,
                'slider_1_title' => NULL,
                'slider_1_sub_title' => NULL,
                'slider_1_description' => NULL,
                'slider_2_title' => NULL,
                'slider_2_sub_title' => NULL,
                'slider_2_description' => NULL,
                'slider_3_title' => NULL,
                'slider_3_sub_title' => NULL,
                'slider_3_description' => NULL,
                'title_1' => NULL,
                'content_1' => NULL,
                'title_2' => NULL,
                'content_2' => NULL,
                'title_3' => NULL,
                'content_3' => NULL,
                'title_4' => NULL,
                'content_4' => NULL,
                'title_5' => NULL,
                'content_5' => NULL,
                'title_6' => NULL,
                'content_6' => NULL,
                'image_1' => NULL,
                'image_2' => NULL,
                'image_3' => NULL,
                'image_4' => NULL,
                'image_5' => NULL,
                'image_6' => NULL,
                'video_url' => NULL,
            ),
            12 => 
            array (
                'id' => 1,
                'uuid' => 'f62db5d2-218c-11ea-b13f-000c29f164c3',
                'type' => 1,
                'sub_type' => 1,
                'title' => 'Papers To Help You',
                'slug' => 'home-banner-section',
                'sub_title' => 'LEARN, PRACTICE & SUCCEED',
                'content' => 'Excellent exam papers designed by experts and classroom tested to help students prepare for grammar and independent schools examinations',
                'note' => '*Immediately download after purchase',
                'subject_title_1' => NULL,
                'subject_title_1_content' => NULL,
                'subject_title_2' => NULL,
                'subject_title_2_content' => NULL,
                'subject_title_3' => NULL,
                'subject_title_3_content' => NULL,
                'subject_title_4' => NULL,
                'subject_title_4_content' => NULL,
                'exam_format_title_1' => NULL,
                'exam_format_title_1_content' => NULL,
                'exam_format_title_2' => NULL,
                'exam_format_title_2_content' => NULL,
                'project_type' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-10-02 11:52:07',
                'deleted_at' => NULL,
                'slider_1_title' => NULL,
                'slider_1_sub_title' => NULL,
                'slider_1_description' => NULL,
                'slider_2_title' => NULL,
                'slider_2_sub_title' => NULL,
                'slider_2_description' => NULL,
                'slider_3_title' => NULL,
                'slider_3_sub_title' => NULL,
                'slider_3_description' => NULL,
                'title_1' => NULL,
                'content_1' => NULL,
                'title_2' => NULL,
                'content_2' => NULL,
                'title_3' => NULL,
                'content_3' => NULL,
                'title_4' => NULL,
                'content_4' => NULL,
                'title_5' => NULL,
                'content_5' => NULL,
                'title_6' => NULL,
                'content_6' => NULL,
                'image_1' => NULL,
                'image_2' => NULL,
                'image_3' => NULL,
                'image_4' => NULL,
                'image_5' => NULL,
                'image_6' => NULL,
                'video_url' => NULL,
            ),
            13 => 
            array (
                'id' => 8,
                'uuid' => '57830b54-219b-11ea-b13f-000c29f164c3',
                'type' => 2,
                'sub_type' => 8,
                'title' => 'We Provide',
                'slug' => 'aboutus-we-provide',
                'sub_title' => NULL,
                'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum rhoncus accumsan nisi suscipit tincidunt. Etiam vestibulum sem felis, in interdum sapien mollis sit amet.

It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
Test',
                'note' => NULL,
                'subject_title_1' => NULL,
                'subject_title_1_content' => NULL,
                'subject_title_2' => NULL,
                'subject_title_2_content' => NULL,
                'subject_title_3' => NULL,
                'subject_title_3_content' => NULL,
                'subject_title_4' => NULL,
                'subject_title_4_content' => NULL,
                'exam_format_title_1' => NULL,
                'exam_format_title_1_content' => NULL,
                'exam_format_title_2' => NULL,
                'exam_format_title_2_content' => NULL,
                'project_type' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-10-05 08:15:12',
                'deleted_at' => NULL,
                'slider_1_title' => NULL,
                'slider_1_sub_title' => NULL,
                'slider_1_description' => NULL,
                'slider_2_title' => NULL,
                'slider_2_sub_title' => NULL,
                'slider_2_description' => NULL,
                'slider_3_title' => NULL,
                'slider_3_sub_title' => NULL,
                'slider_3_description' => NULL,
                'title_1' => NULL,
                'content_1' => NULL,
                'title_2' => NULL,
                'content_2' => NULL,
                'title_3' => NULL,
                'content_3' => NULL,
                'title_4' => NULL,
                'content_4' => NULL,
                'title_5' => NULL,
                'content_5' => NULL,
                'title_6' => NULL,
                'content_6' => NULL,
                'image_1' => NULL,
                'image_2' => NULL,
                'image_3' => NULL,
                'image_4' => NULL,
                'image_5' => NULL,
                'image_6' => NULL,
                'video_url' => NULL,
            ),
            14 => 
            array (
                'id' => 37,
                'uuid' => 'f62db5d2-218c-11ea-b13f-000c29f165c2',
                'type' => 1,
                'sub_type' => 4,
                'title' => 'Why Choose AshACE?',
                'slug' => 'why-choose-ash-ace',
                'sub_title' => '',
                'content' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis',
                'note' => '',
                'subject_title_1' => NULL,
                'subject_title_1_content' => NULL,
                'subject_title_2' => NULL,
                'subject_title_2_content' => NULL,
                'subject_title_3' => NULL,
                'subject_title_3_content' => NULL,
                'subject_title_4' => NULL,
                'subject_title_4_content' => NULL,
                'exam_format_title_1' => NULL,
                'exam_format_title_1_content' => NULL,
                'exam_format_title_2' => NULL,
                'exam_format_title_2_content' => NULL,
                'project_type' => 3,
                'created_at' => '2020-09-30 13:24:41',
                'updated_at' => '2020-10-01 14:01:55',
                'deleted_at' => NULL,
                'slider_1_title' => NULL,
                'slider_1_sub_title' => NULL,
                'slider_1_description' => NULL,
                'slider_2_title' => NULL,
                'slider_2_sub_title' => NULL,
                'slider_2_description' => NULL,
                'slider_3_title' => NULL,
                'slider_3_sub_title' => NULL,
                'slider_3_description' => NULL,
                'title_1' => '01. Loreum Ipsum',
                'content_1' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna quis nostrud',
                'title_2' => '01. Loreum Ipsum',
                'content_2' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna quis nostrud',
                'title_3' => '01. Loreum Ipsum',
                'content_3' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna quis nostrud',
                'title_4' => '01. Loreum Ipsum',
                'content_4' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna quis nostrud',
                'title_5' => '01. Loreum Ipsum',
                'content_5' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna quis nostrud',
                'title_6' => '01. Loreum Ipsum',
                'content_6' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna quis nostrud',
                'image_1' => NULL,
                'image_2' => NULL,
                'image_3' => NULL,
                'image_4' => NULL,
                'image_5' => NULL,
                'image_6' => NULL,
                'video_url' => NULL,
            ),
            15 => 
            array (
                'id' => 11,
                'uuid' => 'f78607ad-219b-11ea-b13f-000c29f164c3',
                'type' => 3,
                'sub_type' => 11,
                'title' => 'Lorem ipsum dolor sit amet',
                'slug' => 'tutions-banner-section',
                'sub_title' => 'Consectetur adipiscing elit',
                'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum rhoncus accumsan nisi suscipit tincidunt. Etiam vestibulum sem felis, in interdum sapien mollis sit amet.
TestLorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum rhoncus accumsan nisi suscipit tincidunt. Etiam vestibulum sem felis, in interdum sapien mollis sit amet.
TestLorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum rhoncus accumsan nisi suscipit tincidunt. Etiam vestibulum sem felis, in interdum sapien mollis sit amet.
Test',
                'note' => NULL,
                'subject_title_1' => '',
                'subject_title_1_content' => '',
                'subject_title_2' => '',
                'subject_title_2_content' => '',
                'subject_title_3' => '',
                'subject_title_3_content' => '',
                'subject_title_4' => '',
                'subject_title_4_content' => '',
                'exam_format_title_1' => '',
                'exam_format_title_1_content' => '',
                'exam_format_title_2' => '',
                'exam_format_title_2_content' => '',
                'project_type' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-11-10 10:48:56',
                'deleted_at' => NULL,
                'slider_1_title' => '',
                'slider_1_sub_title' => '',
                'slider_1_description' => '',
                'slider_2_title' => '',
                'slider_2_sub_title' => '',
                'slider_2_description' => '',
                'slider_3_title' => '',
                'slider_3_sub_title' => '',
                'slider_3_description' => '',
                'title_1' => '',
                'content_1' => '',
                'title_2' => '',
                'content_2' => '',
                'title_3' => '',
                'content_3' => '',
                'title_4' => '',
                'content_4' => '',
                'title_5' => '',
                'content_5' => '',
                'title_6' => '',
                'content_6' => '',
                'image_1' => NULL,
                'image_2' => NULL,
                'image_3' => NULL,
                'image_4' => NULL,
                'image_5' => NULL,
                'image_6' => NULL,
                'video_url' => NULL,
            ),
            16 => 
            array (
                'id' => 12,
                'uuid' => '125ec707-219c-11ea-b13f-000c29f164c3',
                'type' => 3,
                'sub_type' => 12,
                'title' => 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet,',
                'slug' => 'tutions-main-section',
                'sub_title' => NULL,
                'content' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'note' => NULL,
                'subject_title_1' => NULL,
                'subject_title_1_content' => NULL,
                'subject_title_2' => NULL,
                'subject_title_2_content' => NULL,
                'subject_title_3' => NULL,
                'subject_title_3_content' => NULL,
                'subject_title_4' => NULL,
                'subject_title_4_content' => NULL,
                'exam_format_title_1' => NULL,
                'exam_format_title_1_content' => NULL,
                'exam_format_title_2' => NULL,
                'exam_format_title_2_content' => NULL,
                'project_type' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-10-05 08:05:56',
                'deleted_at' => NULL,
                'slider_1_title' => NULL,
                'slider_1_sub_title' => NULL,
                'slider_1_description' => NULL,
                'slider_2_title' => NULL,
                'slider_2_sub_title' => NULL,
                'slider_2_description' => NULL,
                'slider_3_title' => NULL,
                'slider_3_sub_title' => NULL,
                'slider_3_description' => NULL,
                'title_1' => NULL,
                'content_1' => NULL,
                'title_2' => NULL,
                'content_2' => NULL,
                'title_3' => NULL,
                'content_3' => NULL,
                'title_4' => NULL,
                'content_4' => NULL,
                'title_5' => NULL,
                'content_5' => NULL,
                'title_6' => NULL,
                'content_6' => NULL,
                'image_1' => NULL,
                'image_2' => NULL,
                'image_3' => NULL,
                'image_4' => NULL,
                'image_5' => NULL,
                'image_6' => NULL,
                'video_url' => NULL,
            ),
            17 => 
            array (
                'id' => 13,
                'uuid' => '3257c76e-219c-11ea-b13f-000c29f164c3',
                'type' => 3,
                'sub_type' => 13,
                'title' => 'Lorem ipsum dolor sit amet',
                'slug' => 'tutions-sub-section',
                'sub_title' => NULL,
                'content' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
                'note' => NULL,
                'subject_title_1' => NULL,
                'subject_title_1_content' => NULL,
                'subject_title_2' => NULL,
                'subject_title_2_content' => NULL,
                'subject_title_3' => NULL,
                'subject_title_3_content' => NULL,
                'subject_title_4' => NULL,
                'subject_title_4_content' => NULL,
                'exam_format_title_1' => NULL,
                'exam_format_title_1_content' => NULL,
                'exam_format_title_2' => NULL,
                'exam_format_title_2_content' => NULL,
                'project_type' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-10-05 08:09:02',
                'deleted_at' => NULL,
                'slider_1_title' => NULL,
                'slider_1_sub_title' => NULL,
                'slider_1_description' => NULL,
                'slider_2_title' => NULL,
                'slider_2_sub_title' => NULL,
                'slider_2_description' => NULL,
                'slider_3_title' => NULL,
                'slider_3_sub_title' => NULL,
                'slider_3_description' => NULL,
                'title_1' => NULL,
                'content_1' => NULL,
                'title_2' => NULL,
                'content_2' => NULL,
                'title_3' => NULL,
                'content_3' => NULL,
                'title_4' => NULL,
                'content_4' => NULL,
                'title_5' => NULL,
                'content_5' => NULL,
                'title_6' => NULL,
                'content_6' => NULL,
                'image_1' => NULL,
                'image_2' => NULL,
                'image_3' => NULL,
                'image_4' => NULL,
                'image_5' => NULL,
                'image_6' => NULL,
                'video_url' => NULL,
            ),
            18 => 
            array (
                'id' => 36,
                'uuid' => 'f62db5d2-218c-11ea-b13f-000c29f165c1',
                'type' => 1,
                'sub_type' => 3,
                'title' => 'About AshAce',
                'slug' => 'about-ash-ace',
                'sub_title' => '',
                'content' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit',
                'note' => '',
                'subject_title_1' => '',
                'subject_title_1_content' => '',
                'subject_title_2' => '',
                'subject_title_2_content' => '',
                'subject_title_3' => '',
                'subject_title_3_content' => '',
                'subject_title_4' => '',
                'subject_title_4_content' => '',
                'exam_format_title_1' => '',
                'exam_format_title_1_content' => '',
                'exam_format_title_2' => '',
                'exam_format_title_2_content' => '',
                'project_type' => 3,
                'created_at' => '2020-09-30 13:24:41',
                'updated_at' => '2020-12-16 10:55:09',
                'deleted_at' => NULL,
                'slider_1_title' => '',
                'slider_1_sub_title' => '',
                'slider_1_description' => '',
                'slider_2_title' => '',
                'slider_2_sub_title' => '',
                'slider_2_description' => '',
                'slider_3_title' => '',
                'slider_3_sub_title' => '',
                'slider_3_description' => '',
                'title_1' => '',
                'content_1' => '',
                'title_2' => '',
                'content_2' => '',
                'title_3' => '',
                'content_3' => '',
                'title_4' => '',
                'content_4' => '',
                'title_5' => '',
                'content_5' => '',
                'title_6' => '',
                'content_6' => '',
                'image_1' => NULL,
                'image_2' => NULL,
                'image_3' => NULL,
                'image_4' => NULL,
                'image_5' => NULL,
                'image_6' => NULL,
                'video_url' => NULL,
            ),
            19 => 
            array (
                'id' => 43,
                'uuid' => 'f62db5d2-218c-11ea-b13f-000c29f164d1',
                'type' => 1,
                'sub_type' => 10,
                'title' => 'Mock Papers',
                'slug' => 'emock-paper-section',
                'sub_title' => '',
                'content' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat',
                'note' => '',
                'subject_title_1' => '',
                'subject_title_1_content' => '',
                'subject_title_2' => '',
                'subject_title_2_content' => '',
                'subject_title_3' => '',
                'subject_title_3_content' => '',
                'subject_title_4' => '',
                'subject_title_4_content' => '',
                'exam_format_title_1' => '',
                'exam_format_title_1_content' => '',
                'exam_format_title_2' => '',
                'exam_format_title_2_content' => '',
                'project_type' => 1,
                'created_at' => '2020-09-30 13:24:41',
                'updated_at' => '2021-01-07 12:50:27',
                'deleted_at' => NULL,
                'slider_1_title' => 'Mock Papers',
                'slider_1_sub_title' => '',
                'slider_1_description' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat',
                'slider_2_title' => '<h2>Let’s <strong>Practice More </strong> &amp; Achieve Goals!</h2>',
                'slider_2_sub_title' => '',
                'slider_2_description' => '<ul class="bnr_inflist bnr_inflist_v2">
<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
<li>Cras volutpat dolor non quam vehicula ullamcorper sit amet quis augue.
</li>
<li>Quisque nec dui posuere, dignissim augue at, molestie ipsum.</li>
<li>Duis eu neque non leo feugiat feugiat.</li>
<li>Suspendisse commodo nulla eget pretium auctor.</li>
</ul>',
                'slider_3_title' => '<h2>de <strong>Finibus Bonorum</strong> et <br>Malorum</h2>',
                'slider_3_sub_title' => '',
                'slider_3_description' => '<p class="bnr_s_p">accusamus et iusto odio dignissimos ducimus qui blanditiis
praesentium voluptatum deleniti atque corrupti quos dolores et quas
molestias
excepturi sint occaecati cupiditate non provident, similique sunt in culpa
qui
ofﬁcia deserunt mollitiafuga. Et harum quidem r</p>',
                'title_1' => '',
                'content_1' => '',
                'title_2' => '',
                'content_2' => '',
                'title_3' => '',
                'content_3' => '',
                'title_4' => '',
                'content_4' => '',
                'title_5' => '',
                'content_5' => '',
                'title_6' => '',
                'content_6' => '',
                'image_1' => NULL,
                'image_2' => NULL,
                'image_3' => NULL,
                'image_4' => NULL,
                'image_5' => NULL,
                'image_6' => NULL,
                'video_url' => NULL,
            ),
            20 => 
            array (
                'id' => 33,
                'uuid' => 'f62db5d2-218c-11ea-b13f-000c29f164c8',
                'type' => 1,
                'sub_type' => 1,
                'title' => 'Slider',
                'slug' => 'ace-mock-slider-section',
                'sub_title' => 'LEARN, PRACTICE & SUCCEED',
                'content' => '<ul>
<li>Excellent exam papers designed by experts and classroom tested to help students prepare for grammar and independent schools examinations</li>
<li><strong>Covers all subjects</strong> &ndash; English, Verbal Reasoning, Non-Verbal Reasoning and Maths</li>
<li><strong>Covers both formats</strong> &ndash; standard and multiple-choice</li>
<li>Includes GL, CEM and super-selective style exams</li>
</ul>',
                'note' => '*Immediately download after purchase',
                'subject_title_1' => '',
                'subject_title_1_content' => '',
                'subject_title_2' => '',
                'subject_title_2_content' => '',
                'subject_title_3' => '',
                'subject_title_3_content' => '',
                'subject_title_4' => '',
                'subject_title_4_content' => '',
                'exam_format_title_1' => '',
                'exam_format_title_1_content' => '',
                'exam_format_title_2' => '',
                'exam_format_title_2_content' => '',
                'project_type' => 3,
                'created_at' => '2020-09-30 13:24:41',
                'updated_at' => '2021-03-15 05:53:07',
                'deleted_at' => NULL,
                'slider_1_title' => '<h1>An <strong>Online</strong> <strong>Portal</strong> To Help<br />
Your Kids Achieve Their Goals!</h1>',
                'slider_1_sub_title' => '<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat</p>',
                'slider_1_description' => '<ul class="bnr_in_list">
<li>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
</li>
<li>
<p>Cras volutpat dolor non quam vehicula ullamcorper sit amet quis augue.</p>
</li>
</ul>',
                'slider_2_title' => '<h1>An <strong>Online</strong> <strong>Portal</strong> To Help<br />
Your Kids Achieve Their Goals!</h1>',
                'slider_2_sub_title' => '',
                'slider_2_description' => '<ul class="bnr_in_list">
<li>
<p>QE/Wilson/St.Olave\\\'s: 45 Selections</p>
</li>
<li>
<p>Newstead Wood : 51 Selections</p>
</li>
<li>
<p>Kent : Over 100 Selections</p>
</li>
<li>
<p>Bexley : Over 100 Selections</p>
</li>
</ul>',
                'slider_3_title' => '<h1>We provide <strong>customized </strong><br />
<strong>tuition</strong> via online sessions.</h1>',
                'slider_3_sub_title' => '',
                'slider_3_description' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>',
                'title_1' => '',
                'content_1' => '',
                'title_2' => '',
                'content_2' => '',
                'title_3' => '',
                'content_3' => '',
                'title_4' => '',
                'content_4' => '',
                'title_5' => '',
                'content_5' => '',
                'title_6' => '',
                'content_6' => '',
                'image_1' => NULL,
                'image_2' => NULL,
                'image_3' => NULL,
                'image_4' => NULL,
                'image_5' => NULL,
                'image_6' => NULL,
                'video_url' => NULL,
            ),
            21 => 
            array (
                'id' => 16,
                'uuid' => 'e2fb9b2e-f3ed-48c8-92f6-450efcb35ad7',
                'type' => 4,
                'sub_type' => 1,
                'title' => 'Papers',
                'slug' => 'papers',
                'sub_title' => '',
                'content' => '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
                'note' => NULL,
                'subject_title_1' => '',
                'subject_title_1_content' => '',
                'subject_title_2' => '',
                'subject_title_2_content' => '',
                'subject_title_3' => '',
                'subject_title_3_content' => '',
                'subject_title_4' => '',
                'subject_title_4_content' => '',
                'exam_format_title_1' => '',
                'exam_format_title_1_content' => '',
                'exam_format_title_2' => '',
                'exam_format_title_2_content' => '',
                'project_type' => 0,
                'created_at' => '2019-12-31 12:27:30',
                'updated_at' => '2021-08-12 12:19:37',
                'deleted_at' => NULL,
                'slider_1_title' => '',
                'slider_1_sub_title' => '',
                'slider_1_description' => '',
                'slider_2_title' => '',
                'slider_2_sub_title' => '',
                'slider_2_description' => '',
                'slider_3_title' => '',
                'slider_3_sub_title' => '',
                'slider_3_description' => '',
                'title_1' => '',
                'content_1' => '',
                'title_2' => '',
                'content_2' => '',
                'title_3' => '',
                'content_3' => '',
                'title_4' => '',
                'content_4' => '',
                'title_5' => '',
                'content_5' => '',
                'title_6' => '',
                'content_6' => '',
                'image_1' => NULL,
                'image_2' => NULL,
                'image_3' => NULL,
                'image_4' => NULL,
                'image_5' => NULL,
                'image_6' => NULL,
                'video_url' => NULL,
            ),
            22 => 
            array (
                'id' => 46,
                'uuid' => 'f62db5d2-218c-11ea-b13f-000c29f164d4',
                'type' => 1,
                'sub_type' => 13,
                'title' => 'Check your child’s performance in detail with us',
                'slug' => 'emock-child-performance-section',
                'sub_title' => '',
                'content' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci',
                'note' => '',
                'subject_title_1' => '',
                'subject_title_1_content' => '',
                'subject_title_2' => '',
                'subject_title_2_content' => '',
                'subject_title_3' => '',
                'subject_title_3_content' => '',
                'subject_title_4' => '',
                'subject_title_4_content' => '',
                'exam_format_title_1' => '',
                'exam_format_title_1_content' => '',
                'exam_format_title_2' => '',
                'exam_format_title_2_content' => '',
                'project_type' => 1,
                'created_at' => '2020-09-30 13:24:41',
                'updated_at' => '2021-01-07 12:59:41',
                'deleted_at' => NULL,
                'slider_1_title' => '',
                'slider_1_sub_title' => '',
                'slider_1_description' => '',
                'slider_2_title' => '',
                'slider_2_sub_title' => '',
                'slider_2_description' => '',
                'slider_3_title' => '',
                'slider_3_sub_title' => '',
                'slider_3_description' => '',
                'title_1' => 'Keep a track of your child’s result through leaderboard',
                'content_1' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat',
                'title_2' => 'Know your child’s weaker points and help him grow',
                'content_2' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat',
                'title_3' => '',
                'content_3' => '',
                'title_4' => '',
                'content_4' => '',
                'title_5' => '',
                'content_5' => '',
                'title_6' => '',
                'content_6' => '',
                'image_1' => NULL,
                'image_2' => NULL,
                'image_3' => NULL,
                'image_4' => NULL,
                'image_5' => NULL,
                'image_6' => NULL,
                'video_url' => NULL,
            ),
            23 => 
            array (
                'id' => 45,
                'uuid' => 'f62db5d2-218c-11ea-b13f-000c29f164d3',
                'type' => 1,
                'sub_type' => 12,
                'title' => 'Questions prepared just like the real exam ?',
                'slug' => 'emock-question-section',
                'sub_title' => '',
                'content' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci',
                'note' => '',
                'subject_title_1' => '',
                'subject_title_1_content' => '',
                'subject_title_2' => '',
                'subject_title_2_content' => '',
                'subject_title_3' => '',
                'subject_title_3_content' => '',
                'subject_title_4' => '',
                'subject_title_4_content' => '',
                'exam_format_title_1' => '',
                'exam_format_title_1_content' => '',
                'exam_format_title_2' => '',
                'exam_format_title_2_content' => '',
                'project_type' => 1,
                'created_at' => '2020-09-30 13:24:41',
                'updated_at' => '2021-01-07 12:59:41',
                'deleted_at' => NULL,
                'slider_1_title' => '',
                'slider_1_sub_title' => '',
                'slider_1_description' => '',
                'slider_2_title' => '',
                'slider_2_sub_title' => '',
                'slider_2_description' => '',
                'slider_3_title' => '',
                'slider_3_sub_title' => '',
                'slider_3_description' => '',
                'title_1' => '',
                'content_1' => '',
                'title_2' => '',
                'content_2' => '',
                'title_3' => '',
                'content_3' => '',
                'title_4' => '',
                'content_4' => '',
                'title_5' => '',
                'content_5' => '',
                'title_6' => '',
                'content_6' => '',
                'image_1' => NULL,
                'image_2' => NULL,
                'image_3' => NULL,
                'image_4' => NULL,
                'image_5' => NULL,
                'image_6' => NULL,
                'video_url' => NULL,
            ),
            24 => 
            array (
                'id' => 44,
                'uuid' => 'f62db5d2-218c-11ea-b13f-000c29f164d2',
                'type' => 1,
                'sub_type' => 11,
                'title' => 'How Mock Exams Work?',
                'slug' => 'emock-how-exam-work-section',
                'sub_title' => '',
                'content' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci',
                'note' => '',
                'subject_title_1' => '',
                'subject_title_1_content' => '',
                'subject_title_2' => '',
                'subject_title_2_content' => '',
                'subject_title_3' => '',
                'subject_title_3_content' => '',
                'subject_title_4' => '',
                'subject_title_4_content' => '',
                'exam_format_title_1' => '',
                'exam_format_title_1_content' => '',
                'exam_format_title_2' => '',
                'exam_format_title_2_content' => '',
                'project_type' => 1,
                'created_at' => '2020-09-30 13:24:41',
                'updated_at' => '2021-01-07 12:55:33',
                'deleted_at' => NULL,
                'slider_1_title' => 'Mock Papers',
                'slider_1_sub_title' => '',
                'slider_1_description' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat',
                'slider_2_title' => '<h2>Let’s <strong>Practice More </strong> &amp; Achieve Goals!</h2>',
                'slider_2_sub_title' => '',
                'slider_2_description' => '<ul class="bnr_inflist bnr_inflist_v2">
<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
<li>Cras volutpat dolor non quam vehicula ullamcorper sit amet quis augue.
</li>
<li>Quisque nec dui posuere, dignissim augue at, molestie ipsum.</li>
<li>Duis eu neque non leo feugiat feugiat.</li>
<li>Suspendisse commodo nulla eget pretium auctor.</li>
</ul>',
                'slider_3_title' => '<h2>de <strong>Finibus Bonorum</strong> et <br>Malorum</h2>',
                'slider_3_sub_title' => '',
                'slider_3_description' => '<p class="bnr_s_p">accusamus et iusto odio dignissimos ducimus qui blanditiis
praesentium voluptatum deleniti atque corrupti quos dolores et quas
molestias
excepturi sint occaecati cupiditate non provident, similique sunt in culpa
qui
ofﬁcia deserunt mollitiafuga. Et harum quidem r</p>',
                'title_1' => '',
                'content_1' => '',
                'title_2' => '',
                'content_2' => '',
                'title_3' => '',
                'content_3' => '',
                'title_4' => '',
                'content_4' => '',
                'title_5' => '',
                'content_5' => '',
                'title_6' => '',
                'content_6' => '',
                'image_1' => NULL,
                'image_2' => NULL,
                'image_3' => NULL,
                'image_4' => NULL,
                'image_5' => NULL,
                'image_6' => '',
                'video_url' => 'yAoLSRbwxL8',
            ),
            25 => 
            array (
                'id' => 40,
                'uuid' => 'f62db5d2-218c-11ea-b13f-000c29f165c5',
                'type' => 1,
                'sub_type' => 8,
                'title' => 'Subscribe To Our Newsletter To Hear About Special Offers !',
                'slug' => 'subscribe-section',
                'sub_title' => '',
                'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut volutpat sapien nec justo',
                'note' => '',
                'subject_title_1' => NULL,
                'subject_title_1_content' => NULL,
                'subject_title_2' => NULL,
                'subject_title_2_content' => NULL,
                'subject_title_3' => NULL,
                'subject_title_3_content' => NULL,
                'subject_title_4' => NULL,
                'subject_title_4_content' => NULL,
                'exam_format_title_1' => NULL,
                'exam_format_title_1_content' => NULL,
                'exam_format_title_2' => NULL,
                'exam_format_title_2_content' => NULL,
                'project_type' => 3,
                'created_at' => '2020-09-30 13:24:41',
                'updated_at' => '2020-09-30 12:51:47',
                'deleted_at' => NULL,
                'slider_1_title' => NULL,
                'slider_1_sub_title' => NULL,
                'slider_1_description' => NULL,
                'slider_2_title' => NULL,
                'slider_2_sub_title' => NULL,
                'slider_2_description' => NULL,
                'slider_3_title' => NULL,
                'slider_3_sub_title' => NULL,
                'slider_3_description' => NULL,
                'title_1' => NULL,
                'content_1' => NULL,
                'title_2' => NULL,
                'content_2' => NULL,
                'title_3' => NULL,
                'content_3' => NULL,
                'title_4' => NULL,
                'content_4' => NULL,
                'title_5' => NULL,
                'content_5' => NULL,
                'title_6' => NULL,
                'content_6' => NULL,
                'image_1' => NULL,
                'image_2' => NULL,
                'image_3' => NULL,
                'image_4' => NULL,
                'image_5' => NULL,
                'image_6' => NULL,
                'video_url' => NULL,
            ),
            26 => 
            array (
                'id' => 42,
                'uuid' => 'f62db5d2-218c-11ea-b13f-000c29f164d9',
                'type' => 1,
                'sub_type' => 9,
                'title' => 'Slider',
                'slug' => 'emock-exam-slider-section',
                'sub_title' => 'LEARN, PRACTICE & SUCCEED',
                'content' => '',
                'note' => '',
                'subject_title_1' => '',
                'subject_title_1_content' => '',
                'subject_title_2' => '',
                'subject_title_2_content' => '',
                'subject_title_3' => '',
                'subject_title_3_content' => '',
                'subject_title_4' => '',
                'subject_title_4_content' => '',
                'exam_format_title_1' => '',
                'exam_format_title_1_content' => '',
                'exam_format_title_2' => '',
                'exam_format_title_2_content' => '',
                'project_type' => 1,
                'created_at' => '2020-09-30 13:24:41',
                'updated_at' => '2021-03-15 11:33:02',
                'deleted_at' => NULL,
                'slider_1_title' => '<h2>Let&rsquo;s <strong>Practice More </strong> &amp; Achieve Goals!</h2>',
                'slider_1_sub_title' => '',
                'slider_1_description' => '<ul>
<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
<li>Quisque nec dui posuere, dignissim augue at, molestie ipsum.</li>
<li>Duis eu neque non leo feugiat feugiat.</li>
<li>Suspendisse commodo nulla eget pretium auctor.</li>
</ul>',
                'slider_2_title' => '<h2>Let&rsquo;s <strong>Practice More </strong> &amp; Achieve Goals!</h2>',
                'slider_2_sub_title' => '',
                'slider_2_description' => '<ul>
<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
<li>Cras volutpat dolor non quam vehicula ullamcorper sit amet quis augue.</li>
<li>Quisque nec dui posuere, dignissim augue at, molestie ipsum.</li>
<li>Duis eu neque non leo feugiat feugiat.</li>
<li>Suspendisse commodo nulla eget pretium auctor.</li>
</ul>',
                'slider_3_title' => '<h2>Let&rsquo;s Practice More &amp; Achieve Goals!</h2>',
                'slider_3_sub_title' => '',
                'slider_3_description' => '<ul>
<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
<li>Cras volutpat dolor non quam vehicula ullamcorper sit amet quis augue.</li>
<li>Quisque nec dui posuere, dignissim augue at, molestie ipsum.</li>
<li>Duis eu neque non leo feugiat feugiat.</li>
<li>Suspendisse commodo nulla eget pretium auctor.</li>
</ul>',
                'title_1' => '',
                'content_1' => '',
                'title_2' => '',
                'content_2' => '',
                'title_3' => '',
                'content_3' => '',
                'title_4' => '',
                'content_4' => '',
                'title_5' => '',
                'content_5' => '',
                'title_6' => '',
                'content_6' => '',
                'image_1' => NULL,
                'image_2' => NULL,
                'image_3' => NULL,
                'image_4' => NULL,
                'image_5' => NULL,
                'image_6' => NULL,
                'video_url' => NULL,
            ),
        ));
        
        
    }
}