<?php

use function PHPSTORM_META\map;

return [
    'websetting'=>[
        'logo_extension'=>'jpg,jpeg,png',
        'logo_size'=>'2',
        'favicon_extension'=>'svg,png,ico',
        'favicon_size'=>'2',
        'url'=>true,
        'logo_height'=>'100px',
        'logo_width'=>'100px',
        'favicon_width'=>'100px',
        'favicon_height'=>'100px',
        'active_tab'=>[
            // 1=>'general_tab',
            2=>'promo_code',
            3=>'meta_tab',
            4=>'social_media_tab',
            5=>'rating_mail',
            6=>'notification',
            7=>'stripe_payment',
            8=>'paypal_payment',
        ]
    ],
    'image_storage' => [
        'storage_path' => '/app/public/uploads',
    ],
    'paper_category' => [
        'folder_name' => 'papercategory',
        'directory_path' => 'storage/app/papercategory/',
    ],
    'subject'=>[
        'folder_name'=>'subject',
        'directory_path' => 'storage/app/subject/',
    ],
    'examtypes'=>[
        'folder_name'=>'examtypes',
        'directory_path' => 'storage/app/examtypes/',
        'select_paper_category' => 'Selecr Paper Category Id'
    ],
    'paper'=>[
        'folder_name'=>'paper',
        'directory_path' => 'storage/app/paper/',
        'image_path' => 'storage/app/public/uploads/',
        'version_name' => '/version-',
    ],
    'storage_path' => 'storage/app/',
    'aa' => 64,
    'avatar_img_height' => 64,
    'status_inactive_value' => 0,
    'status_active_value' => 1,
    'status_deactivate_value' => 2,
    'active' => 'Active',
    'inactive' => 'Inactive',
    'deactivate' => 'Deactivate',
    'yes'=>'Yes',
    'no' =>'No',
    'select' => 'Select',
    'delete' => 'Delete',
    'default_currency_symbol' => '£',
    'percentage_symbol' => '%',
    'blocks' => [
        'ePaper' => [
            'home' => [
                'banner_section' => 'home-banner-section',
                'designed_by_experts' => 'home-designed-by-experts',
                'all_subjects' => 'home-all-subjects',
                'exam_formats' => 'home-exam-formats',
                'exam_styles' => 'home-exam-styles',
            ],
            'about_us' => [
                'banner_section' => 'aboutus-banner-section',
                'main_section' => 'aboutus-main-section',
                'we_provide' => 'aboutus-we-provide',
                'mind_behind_scene' => 'aboutus-mind-behind-the-scene',
                'sub_section' => 'aboutus-sub-section',
            ],
            'tutions' => [
                'banner_section' => 'tutions-banner-section',
                'main_section' => 'tutions-main-section',
                'sub_section' => 'tutions-sub-section',
            ],
            'papers' =>[
                'banner_section' => 'papers-banner-section',
            ]
        ],
        'aceMock' => [
            'home' => [
                'banner_section' => 'ace-mock-slider-section',
                'our_module_section' => 'our-module-section',
                'about_ash_ace' => 'about-ash-ace',
                'why_choose_ash_ace'=>'why-choose-ash-ace',
                'video_section' => 'video-section',
                'help_section' => 'help-section',
                'school_section' => 'school-section',
                'subscribe_section' => 'subscribe-section',
            ],
            'emock' => [
                'banner_section' => 'emock-exam-slider-section',
                'paper_section' => 'emock-paper-section',
                'how_exam_work_section' => 'emock-how-exam-work-section',
                'question_section' => 'emock-question-section',
                'child_performance_section' => 'emock-child-performance-section',
            ],
        ],
        'practice' => [
            'home' => [
                'banner_section' => 'practice-slider-section',
                'our_module_section' => 'practice-our-module-section',
                'about_ash_ace' => 'practice-about-ash-ace',
                'why_choose_ash_ace'=>'practice-why-choose-ash-ace',
                'video_section' => 'practice-video-section',
                'help_section' => 'practice-help-section',
                'school_section' => 'practice-school-section',
                'subscribe_section' => 'practice-subscribe-section',
                'pay_section' => 'practice-how-much-to-pay'
            ],
            'practice' => [
                'banner_section' => 'practice-exam-slider-section',
                'paper_section' => 'practice-paper-section',
                'how_exam_work_section' => 'practice-how-exam-work-section',
                'question_section' => 'practice-question-section',
                'child_performance_section' => 'practice-child-performance-section',
                'past_paper_section'=> 'practice-by-past-paper',
                'topic_section'=> 'practice-by-topic',
                'practice_section' => 'practice-by-weekly-assessment',
                'practice_section_detail' => 'practice-by-weekly-assessment-detail',
                'past_paper_section_detail'=> 'practice-by-past-paper-detail',
            ],
        ],
    ],
    'block_sections' => [
        'ePaper' => [
            'home-banner-section' => 'Section 1',
            'home-designed-by-experts' => 'Section 2',
            'home-all-subjects' => 'Section 3',
            'home-exam-formats' => 'Section 4',
            'home-exam-styles' => 'Section 5',
            'aboutus-banner-section' => 'Section 1',
            'aboutus-main-section' => 'Section 2',
            'aboutus-we-provide' => 'Section 3',
            'aboutus-mind-behind-the-scene' => 'Section 4',
            'aboutus-sub-section' => 'Section 5',
            'tutions-banner-section' => 'Section 1',
            'tutions-main-section' => 'Section 2',
            'tutions-sub-section' => 'Section 3',
        ],
        'aceMock' =>[

        ],
    ],
    'block_types' => [
        'ePaper' => [
            'home' => 1,
            'about_us' => 2,
            'tutions' => 3,
            'papers' =>4,
        ],
        'aceMock' => [
            'home' => 1,
        ],
        'practice' => [
            'home' => 1,
        ],
    ],
    'block_sub_types' => [
        'ePaper'=>[
            'home_banner_section' => 1,
            'home_designed_by_experts' => 2,
            'home_all_subjects' => 3,
            'home_exam_formats' => 4,
            'home_exam_styles' => 5,
            'aboutus_banner_section' => 6,
            'aboutus_main_section' => 7,
            'aboutus_we_provide' => 8,
            'aboutus_mind_behind_the_scene' => 9,
            'aboutus_sub_section' => 10,
            'tutions_banner_section' => 11,
            'tutions_main_section' => 12,
            'tutions_sub_section' => 13,
        ],
        'aceMock' =>[
            'home_banner_section' => 1,
            'our_module_section' => 2,
            'about_ash_ace' => 3,
            'why_choose_ash_ace' => 4,
            'video_section' => 5,
            'help_section' => 7,
            'school_section' => 6,
            'subscribe_section' => 8,
            'banner_section' =>9,
            'paper_section' =>10,
            'how_exam_work_section' =>11,
            'question_section' =>12,
            'child_performance_section' =>13,
        ],
        'practice' =>[
            'banner_section' =>1,
            'our_module_section' => 2,
            'about_ash_ace' => 3,
            'why_choose_ash_ace' => 4,
            'video_section' => 5,
            'help_section' => 7,
            'school_section' => 6,
            'pay_section' => 9,
            'practice_section' => 10,
            'topic_section' =>11,
            'past_paper_section' => 12,
            'practice_section_detail' => 13,
            'past_paper_section_detail' => 14,
        ],
    ],
    'age' => [
        '7 - 8' => '7 - 8',
        '8 - 9' => '8 - 9',
        '9 - 10' => '9 - 10',
        '10 - 11' => '10 - 11',
    ],

    'date_display_format' => 'd-m-Y',
    'date_display_format_js' => 'MM/DD/YYYY',
    'review_active_value'=>1,
    'review_inactive_value'=>2,
    'review_active'=>'publish',
    'review_inactive'=>'unpublish',
    'payment_paid'=>'paid',
    'payment_unpaid'=>'unpaid',
    'order_pending'=>'pending',
    'order_completed'=>'completed',

    // For Resources
    'resource_store_folder' => 'resources/',
    'resource_directory_path' => 'storage/app/resources/',
    'resource_download_path' => 'app/resources/',

    'user_profile_folder' => 'users/',
    'child_profile_folder' => 'childs/',
    'app_path' => 'storage/app/',

    // For Resources Guidance
    'guidance_store_folder' => 'resources_guidance/',
    'guidance_directory_path' => 'storage/app/resources_guidance/',
    'guidance_download_path' => 'app/resources_guidance/',
    'featured_img_width' => 639,
    'featured_img_height' => 324,
    'editor_img_store_folder' => 'resources_guidance/editor-image/',
    'editor_img_directory_path' => 'storage/app/resources_guidance/editor-image/',

    // Datatable Column Type
    'col_action' => 'action',
    'col_checkbox' => 'checkbox',
    'col_show' => 'show',

    // Test Paper Image Height & Width
    'test_paper_height' => 425,
    'test_paper_width' => 300,
    'thumb_test_paper_height' => 275,
    'thumb_test_paper_width' => 209,

    'input_title_max_length'  => 199,
    'input_desc_max_length' => 300,
    'input_email_max_length' => 50,

    'no_result_found' => "No result found.",

    'blog_type' => ['guidance', 'blog', 'emock-blog'],
    'min_pdf_version'=>1.4,
    'max_pdf_version'=>1.5,
    'email_template'=>[
        1 => 'order-email-to-user',
        2 => 'order-email-to-admin',
        3 => 'contact-us',
        4 => 'review-feedback',
        5 => 'review-feedback-reminder',
        6 => 'resend-order-paper-email-to-user',//
        7=>'purhased-order',
        8=>'update-password',
        9=>'review-and-rate',
        10=>'forgot-password',
        11=>'parent-registration',
        12=>'child-login-detail',
        13=>'payment-detail',//
        14=>'invoice',
    ],
    'email_template_slugs'=>[
        'order_email_to_user' => 'order-email-to-user',
        'order_email_to_admin' => 'order-email-to-admin',
        'contact_us' => 'contact-us',
        'review_feedback' => 'review-feedback',
        'review_feedback_reminder' => 'review-feedback-reminder',
        'resend_order_paper' => 'resend-order-paper-email-to-user',
    ],

    'rules' => [
        'text_length' => 100,
        'content_length' => 1000,
        'name_length' => 191,
        'user_name_length' => 50,
        'password_max_length' => 16,
        'password_min_length' => 6,
        'email_length' => 50,
        'phone_length' => 10,
        'price_length' => 10,
        'question_length' => 3,
        'time_length' => 3,
        'interval_length'=>3,
        'mark_length' =>2,
        'zipcode_length'=>9,
        'phone_max_length' => 12,
        'card_no_max_length' => 16,
        'card_no_min_length' => 6,
        'cvv_length' => 3,
    ],
    'question_type'=>[
        1=>'MCQ',
        2=>'Comprehension',
        3=>'Cloze',
        4=>'Compound Word',
        // 4=>'1-column',
        // 5=>'2-column'
    ],
    'mock-test' => [
        'folder_name' => 'MockExam',
        'storage_path' => 'app/MockExam/',
        'url_path' => 'storage/app/MockExam/',
    ],
    'mock-test-paper' => [
        'folder_name' => 'mock-paper',
        'storage_path' => 'app/mock-paper',
        'url_path' => 'storage/app/mock-paper',
    ],
    'test-assessment' => [
        'folder_name' => 'TestAssessment',
        'storage_path' => 'app/TestAssessment/',
        'url_path' => 'storage/app/TestAssessment/',
    ],
    'image' => [
        'storage_path' => 'app/public/uploads/',
        'url_path' => 'storage/app/public/uploads/',
    ],
    'question-list' => [
        'folder_name' => 'questionList',
        'storage_path' => 'app/questionList',
        'url_path' => 'storage/app/questionList',
    ],
    'passage' => [
        'folder_name' => 'passage',
        'storage_path' => 'app/passage',
        'url_path' => 'storage/app/passage',
    ],
    'cms' => [
        'folder_name' => 'cms',
    ],
    'active_0' => 0,
    'active_1' => 1,
    'active_2' => 2,
    'active_3' => 3,
    'active_4' => 4,
    'active_5' => 5,

    'cms_type' => [
        1 => 'general',
        2 => 'subject',
        3 => 'school'
    ],
    'admin' =>'admin',
    'role' => [
        1 => 'superadmin',
    ],

    'frontend' => 'frontend',
    'APPROVED' => 'APPROVED',
    'COMPLETED' => 'COMPLETED',
    'is_tution_parent'=>[
        0 => 'No',
        1 => 'Yes',
    ],
    'gender'=>[
        0 =>'Male',
        1 => 'Female',
    ],
    'project_type'=>[
        0 => 'Ace Paper',
        1 => 'Ace Mock',
        2 => 'Ace Practice'
    ],
    'questionSubType' => [
        1=>'MCQ Question',
        2=>'Standard Question',
    ],
    'media_type'=>[
        1 => 'Image',
        2 => 'pdf',
    ],
    'thumb' => '/thumb/',
    'banner' => '/banner/',

    'frontend_about' => [
        'bottom_png' => 'frontend/images/bottom_about.png',
        'team_img' => 'frontend/images/team_img.jpg',
    ],

    'frontend_contact_us' => [
        'captcha_png' => 'storage/app/frontend/captcha/captcha.png',
    ],
    'exam_style' =>[
        1=>'MCQ',
        2=>'Standard',
    ],
    'bgColor' =>[
        'pink-bg' => 0,
        'green-bg' => 1,
        'lightgrn-bg' => 2,
        'orange-bg' => 3,
        'blue-bg' => 4,
    ],
    'bgColor2' =>[
        0 => 'pink-bg',
        1 => 'green-bg',
        2 => 'lightgrn-bg',
        3 => 'orange-bg',
        4 => 'blue-bg',
    ],
    'mockFilter' =>[
        '' => 'Exam Type',
        1 => 'MCQ',
        2 => 'Standard',
    ],

    'intervalList' =>[
        1 => 'At the beginning of the test',
        2 => 'At the end of the test',
        3 => 'At Half time',
        4 => 'Last 1 min remaining'
    ],

    'mock_report_type' => [
        1 => 'Number of Student Attempt Test',
        2 => 'Number of Student Joined',
        3 => 'Number of Mock Paper Sold',
        4 => 'E-Papers',
    ],

    'counties' =>[
        'Bedfordshire',
        'Buckinghamshire',
        'Cambridgeshire',
        'Cheshire',
        'Cleveland',
        'Cornwall',
        'Cumbria',
        'Derbyshire',
        'Devon',
        'Dorset',
        'Durham',
        'East Sussex',
        'Essex',
        'Gloucestershire',
        'Greater London',
        'Greater Manchester',
        'Hampshire',
        'Hertfordshire',
        'Kent',
        'Lancashire',
        'Leicestershire',
        'Lincolnshire',
        'Merseyside',
        'Norfolk',
        'North Yorkshire',
        'Northamptonshire',
        'Northumberland',
        'Nottinghamshire',
        'Oxfordshire',
        'Shropshire',
        'Somerset',
        'South Yorkshire',
        'Staffordshire',
        'Suffolk',
        'Surrey',
        'Tyne and Wear',
        'Warwickshire',
        'West Berkshire',
        'West Midlands',
        'West Sussex',
        'West Yorkshire',
        'Wiltshire',
        'Worcestershire',
        'Flintshire',
        'Glamorgan',
        'Merionethshire',
        'Monmouthshire',
        'Montgomeryshire',
        'Pembrokeshire',
        'Radnorshire',
        'Anglesey',
        'Breconshire',
        'Caernarvonshire',
        'Cardiganshire',
        'Carmarthenshire',
        'Denbighshire',
        'Aberdeen City',
        'Aberdeenshire',
        'Angus',
        'Argyll and Bute',
        'City of Edinburgh',
        'Clackmannanshire',
        'Dumfries and Galloway',
        'Dundee City',
        'East Ayrshire',
        'East Dunbartonshire',
        'East Lothian',
        'East Renfrewshire',
        'Eilean Siar',
        'Falkirk',
        'Fife',
        'Glasgow City',
        'Highland',
        'Inverclyde',
        'Midlothian',
        'Moray',
        'North Ayrshire',
        'North Lanarkshire',
        'Orkney Islands',
        'Perth and Kinross',
        'Renfrewshire',
        'Scottish Borders',
        'Shetland Islands',
        'South Ayrshire',
        'South Lanarkshire',
        'Stirling',
        'West Dunbartonshire',
        'West Lothian',
        'Antrim',
        'Armagh',
        'Down',
        'Fermanagh',
        'Derry and Londonderry',
        'Tyrone',
        'Other',
    ],
    'resource_type' =>[
        'sample-papers' => 'Sample Papers List',
        'past-papers' => 'Past Papers List',
        'guidance' => 'Guidance List',
    ],
    'module_type' => [
        0 => 'E-Paper',
        1 => 'E-Mock',
        2 => 'Practice By Weekly Assessment',
        3 => 'Practice By Topic',
    ],
    'past-paper' => [
        'folder_name' => 'paperQuestion',
        'storage_path' => 'app/paperQuestion/',
        'url_path' => 'storage/app/paperQuestion/',
    ],
    'avatar_img_width' => 64,
    'avatar_img_height' => 64,
    'excellent_min' => 90,
    'excellent_max' => 100,
    'very_good_min' => 80,
    'very_good_max' => 89,
    'good_min' => 70,
    'good_max' => 79,
    'fair_min' => 55,
    'fair_max' => 69,
    'improve_min' => 0,
    'improve_max' => 54,
    'subscriptionStatus' => [
        '' => 'Select',
        '0' => 'DeActive',
        '1' => 'Active',
    ],
    'answer_type' => [
        2 => 'Incorrect',
        3 => 'Fairly Correct',
        4 => 'Half Correct',
        5 => 'Mostly Correct',
        1 => 'Fully Correct',
    ],
    'member_type' => [
        1 => 'All Member',
        2 => 'Premium Member'
    ],
    'school_year' =>[
        4 => 4,
        5 => 5,
        6 => 6,
    ],
];
?>
